site_name: Metis Documentation
theme:
  icon:
    repo: fontawesome/brands/github
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - header.autohide
    - navigation.instant
    - navigation.tabs
    - search.suggest
    - navigation.sections
  palette:
    primary: red
extra_css:
  - stylesheets/extra.css
extra:
  homepage: https://metisbot.xyz
repo_url: https://github.com/Frostplexx/DnD_Helper
repo_name: Frostplexx/DnD_Helper
plugins:
  - git-revision-date
  - search:
      lang: en
markdown_extensions:
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Home: 'index.md'
  - Installation: 
    - Setup: 'installation.md'
    - Customization: "customization.md"
    - Google Form: "googleform.md"
    - Deploying: "deployment.md"
  - Commands: 
    - Commands: "commands.md"
    - Campaign: "campaign.md"
    - Buttons: "buttons.md"
    - Utility: "utility.md"
    - Development: "development.md"