site_name: Metis Documentation
theme:
  icon:
    repo: fontawesome/brands/github
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - header.autohide
    - navigation.instant
    - navigation.tabs
    - search.suggest
    - navigation.sections
    - toc.integrate
  palette:
    primary: red
extra_css:
  - stylesheets/extra.css
extra:
  homepage: https://metisbot.xyz
repo_url: https://github.com/Frostplexx/MetisDocs
repo_name: Frostplexx/MetisDocs
plugins:
  - git-revision-date
  - search:
      lang: en
markdown_extensions:
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Home: 
    - Home: 'index.md'
    - General Info: generalInfo.md
  - Installation: 
    - Setup: 'installation/installation.md'
    - Customization: "installation/customization.md"
    - Google Form: "installation/googleform.md"
    - Deploying: "installation/deployment.md"
  - Commands: 
    - Commands: "commands/commands.md"
    - Campaign: "commands/campaign.md"
    - Buttons: "commands/buttons.md"
    - Utility: "commands/utility.md"
    - Development: "commands/development.md"
    - Players: "commands/players.md"
  - Development:
    - Introduction: "development/development.md"
    - Commands: "development/commands.md"
    - Campaigns: "development/campaigns.md"
    - Player Flow: "playersignup.md"
    - Buttons: "development/buttons.md"
    - Event Handling: "development/events.md"
    - VPS Settings: "development/vps.md"